-- 005_better_auth.up.sql
-- Better Auth (https://better-auth.com) lives inside the Next.js
-- process and stores its user / session / organization tables in the
-- same Postgres database as the audit tables. This migration is
-- generated by `npx @better-auth/cli generate` and committed verbatim
-- so we have a reproducible, version-controlled schema.
--
-- To regenerate after changing plugins:
--   cd web && npx @better-auth/cli generate --output ../api/internal/storage/postgres/migrations/005_better_auth.up.sql

BEGIN;

create table if not exists "user" (
    "id" text not null primary key,
    "name" text not null,
    "email" text not null unique,
    "emailVerified" boolean not null,
    "image" text,
    "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
    "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create table if not exists "session" (
    "id" text not null primary key,
    "expiresAt" timestamptz not null,
    "token" text not null unique,
    "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
    "updatedAt" timestamptz not null,
    "ipAddress" text,
    "userAgent" text,
    "userId" text not null references "user" ("id") on delete cascade,
    "activeOrganizationId" text
);

create table if not exists "account" (
    "id" text not null primary key,
    "accountId" text not null,
    "providerId" text not null,
    "userId" text not null references "user" ("id") on delete cascade,
    "accessToken" text,
    "refreshToken" text,
    "idToken" text,
    "accessTokenExpiresAt" timestamptz,
    "refreshTokenExpiresAt" timestamptz,
    "scope" text,
    "password" text,
    "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
    "updatedAt" timestamptz not null
);

create table if not exists "verification" (
    "id" text not null primary key,
    "identifier" text not null,
    "value" text not null,
    "expiresAt" timestamptz not null,
    "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
    "updatedAt" timestamptz default CURRENT_TIMESTAMP not null
);

create table if not exists "organization" (
    "id" text not null primary key,
    "name" text not null,
    "slug" text not null unique,
    "logo" text,
    "createdAt" timestamptz not null,
    "metadata" text
);

create table if not exists "member" (
    "id" text not null primary key,
    "organizationId" text not null references "organization" ("id") on delete cascade,
    "userId" text not null references "user" ("id") on delete cascade,
    "role" text not null,
    "createdAt" timestamptz not null
);

create table if not exists "invitation" (
    "id" text not null primary key,
    "organizationId" text not null references "organization" ("id") on delete cascade,
    "email" text not null,
    "role" text,
    "status" text not null,
    "expiresAt" timestamptz not null,
    "createdAt" timestamptz default CURRENT_TIMESTAMP not null,
    "inviterId" text not null references "user" ("id") on delete cascade
);

create table if not exists "jwks" (
    "id" text not null primary key,
    "publicKey" text not null,
    "privateKey" text not null,
    "createdAt" timestamptz not null,
    "expiresAt" timestamptz
);

create index if not exists "session_userId_idx" on "session" ("userId");
create index if not exists "account_userId_idx" on "account" ("userId");
create index if not exists "verification_identifier_idx" on "verification" ("identifier");
create unique index if not exists "organization_slug_uidx" on "organization" ("slug");
create index if not exists "member_organizationId_idx" on "member" ("organizationId");
create index if not exists "member_userId_idx" on "member" ("userId");
create index if not exists "invitation_organizationId_idx" on "invitation" ("organizationId");
create index if not exists "invitation_email_idx" on "invitation" ("email");

COMMIT;
