package audit

import (
	"context"
	"fmt"
	"io"
	"sort"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// renderPDF builds an audit report with verification results, recorded events
// and an explicit explanation of the evidence limitations.
func renderPDF(ctx context.Context, w io.Writer, svc *Service, in PDFInput) error {
	if in.From.IsZero() {
		in.From = historyStart
	}
	if in.To.IsZero() {
		in.To = farFuture
	}
	if in.VerifyURL == "" {
		in.VerifyURL = "/v1/verify"
	}

	// Use VerifyDeep so the PDF shows every broken event, not just the first.
	verify, err := svc.VerifyDeep(ctx, in.TenantID, in.From, in.To)
	if err != nil {
		return fmt.Errorf("computing chain verification: %w", err)
	}

	// Build a set of broken event IDs for O(1) row-colouring in the event log.
	brokenSet := make(map[string]BrokenEvent, len(verify.AllBrokenEvents))
	for _, b := range verify.AllBrokenEvents {
		brokenSet[b.EventID] = b
	}

	actionCounts, err := svc.repo.CountByAction(ctx, in.TenantID, in.From, in.To)
	if err != nil {
		return fmt.Errorf("counting by action: %w", err)
	}
	actorCounts, err := svc.repo.CountByActorType(ctx, in.TenantID, in.From, in.To)
	if err != nil {
		return fmt.Errorf("counting by actor type: %w", err)
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 20)
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Arial", "I", 8)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(0, 8,
			fmt.Sprintf("Generated by Fact0 Audit. Verify integrity at %s    Page %d of {nb}",
				in.VerifyURL, pdf.PageNo()),
			"", 0, "C", false, 0, "")
	})
	pdf.AliasNbPages("")

	renderCover(pdf, in, verify)
	renderTamperEvidence(pdf, in, verify)
	renderSummaries(pdf, actionCounts, actorCounts)
	if err := renderEventLog(ctx, pdf, svc, in, brokenSet); err != nil {
		return err
	}
	renderLimitationsAppendix(pdf)

	if err := pdf.Output(w); err != nil {
		return fmt.Errorf("writing pdf: %w", err)
	}
	return nil
}

// ─── Sections ──────────────────────────────────────────────

func renderCover(pdf *gofpdf.Fpdf, in PDFInput, v *VerifyResult) {
	pdf.AddPage()
	pdf.SetTextColor(20, 20, 20)

	pdf.SetFont("Arial", "B", 22)
	pdf.Ln(40)
	pdf.CellFormat(0, 12, "Audit Trail Report", "", 1, "C", false, 0, "")

	pdf.SetFont("Arial", "", 12)
	pdf.SetTextColor(80, 80, 80)
	pdf.Ln(4)
	pdf.CellFormat(0, 8, "Recorded audit evidence - Fact0", "", 1, "C", false, 0, "")

	pdf.Ln(20)
	pdf.SetFont("Arial", "", 11)
	pdf.SetTextColor(0, 0, 0)
	box := func(label, value string) {
		pdf.SetFont("Arial", "B", 10)
		pdf.CellFormat(50, 7, label, "", 0, "L", false, 0, "")
		pdf.SetFont("Arial", "", 10)
		pdf.CellFormat(0, 7, value, "", 1, "L", false, 0, "")
	}
	box("Tenant", fmt.Sprintf("%s (%s)", in.TenantName, in.TenantID))
	if in.From.Equal(historyStart) && in.To.Equal(farFuture) {
		box("Period", "All recorded audit history")
	} else {
		box("Period start", in.From.UTC().Format(time.RFC3339))
		box("Period end", in.To.UTC().Format(time.RFC3339))
	}
	box("Events covered", fmt.Sprintf("%d", v.EventsChecked))
	box("Generated at", time.Now().UTC().Format(time.RFC3339))
}

func renderTamperEvidence(pdf *gofpdf.Fpdf, in PDFInput, v *VerifyResult) {
	pdf.AddPage()
	heading(pdf, "1. Tamper-evidence")

	pdf.SetFont("Arial", "", 10)
	intro := "Each event in this log stores the SHA-256 hash of the previous event for the same tenant. " +
		"Verification checks hashes and preceding links in the stored history. A passing result does not " +
		"establish complete capture or prevent an administrator from replacing the database and keys."
	pdf.MultiCell(0, 5, intro, "", "L", false)
	pdf.Ln(4)

	kv := func(k, val string) {
		pdf.SetFont("Arial", "B", 10)
		pdf.CellFormat(45, 7, k, "", 0, "L", false, 0, "")
		pdf.SetFont("Arial", "", 10)
		pdf.CellFormat(0, 7, val, "", 1, "L", false, 0, "")
	}

	if v.Valid {
		kv("Verification status", "VALID - chain intact")
		kv("Events checked", fmt.Sprintf("%d", v.EventsChecked))
		kv("Root hash", truncate(v.RootHash, 80))
	} else {
		// Status row in red
		pdf.SetFont("Arial", "B", 10)
		pdf.CellFormat(45, 7, "Verification status", "", 0, "L", false, 0, "")
		pdf.SetTextColor(180, 30, 30)
		pdf.CellFormat(0, 7,
			fmt.Sprintf("INVALID - %d chain integrity failure(s)", v.BrokenCount),
			"", 1, "L", false, 0, "")
		pdf.SetTextColor(0, 0, 0)

		kv("Events checked", fmt.Sprintf("%d", v.EventsChecked))
		kv("Last valid hash", truncate(v.RootHash, 80))

		pdf.Ln(4)

		// Broken-events table - list every affected event
		pdf.SetFont("Arial", "B", 10)
		pdf.CellFormat(0, 6, fmt.Sprintf("Broken events (%d)", v.BrokenCount), "", 1, "L", false, 0, "")
		pdf.Ln(1)

		pdf.SetFont("Arial", "B", 8)
		pdf.SetFillColor(255, 230, 230)
		pdf.SetDrawColor(200, 80, 80)
		pdf.CellFormat(12, 6, "Seq", "1", 0, "C", true, 0, "")
		pdf.CellFormat(48, 6, "Event ID", "1", 0, "L", true, 0, "")
		pdf.CellFormat(30, 6, "Timestamp (UTC)", "1", 0, "L", true, 0, "")
		pdf.CellFormat(28, 6, "Action", "1", 0, "L", true, 0, "")
		pdf.CellFormat(22, 6, "Actor", "1", 0, "L", true, 0, "")
		pdf.CellFormat(0, 6, "Reason", "1", 1, "L", true, 0, "")

		pdf.SetFont("Arial", "", 7.5)
		pdf.SetFillColor(255, 248, 248)
		for i, b := range v.AllBrokenEvents {
			fill := (i % 2) == 0
			pdf.SetFillColor(255, 248, 248)
			pdf.CellFormat(12, 5, fmt.Sprintf("%d", b.SequenceNumber), "1", 0, "R", fill, 0, "")
			pdf.CellFormat(48, 5, truncate(b.EventID, 26), "1", 0, "L", fill, 0, "")
			pdf.CellFormat(30, 5, b.Timestamp.UTC().Format("2006-01-02 15:04:05"), "1", 0, "L", fill, 0, "")
			pdf.CellFormat(28, 5, truncate(b.Action, 15), "1", 0, "L", fill, 0, "")
			pdf.CellFormat(22, 5, truncate(b.ActorID, 12), "1", 0, "L", fill, 0, "")
			pdf.CellFormat(0, 5, b.Reason, "1", 1, "L", fill, 0, "")
			if pdf.GetY() > 265 {
				pdf.AddPage()
				// Redraw broken-events header on overflow
				pdf.SetFont("Arial", "B", 8)
				pdf.SetFillColor(255, 230, 230)
				pdf.CellFormat(12, 6, "Seq", "1", 0, "C", true, 0, "")
				pdf.CellFormat(48, 6, "Event ID", "1", 0, "L", true, 0, "")
				pdf.CellFormat(30, 6, "Timestamp (UTC)", "1", 0, "L", true, 0, "")
				pdf.CellFormat(28, 6, "Action", "1", 0, "L", true, 0, "")
				pdf.CellFormat(22, 6, "Actor", "1", 0, "L", true, 0, "")
				pdf.CellFormat(0, 6, "Reason", "1", 1, "L", true, 0, "")
				pdf.SetFont("Arial", "", 7.5)
			}
		}
		pdf.SetDrawColor(0, 0, 0)
		pdf.SetFillColor(255, 255, 255)

		pdf.Ln(6)

		// Incident summary box
		pdf.SetFillColor(255, 245, 245)
		pdf.SetDrawColor(200, 80, 80)
		pdf.SetFont("Arial", "B", 10)
		pdf.SetTextColor(160, 30, 30)
		pdf.CellFormat(0, 6, "Incident Summary", "LTR", 1, "L", true, 0, "")
		pdf.SetFont("Arial", "", 9)
		pdf.SetTextColor(80, 30, 30)
		incident := fmt.Sprintf(
			"The SHA-256 hash chain for this tenant has %d verifiable break(s). "+
				"All events highlighted in red in the event log (Section 3) are affected. "+
				"Earlier checked records passed the configured verification recipe.\n\n"+
				"Possible causes:\n"+
				"  1. A database migration or administrative query modified a hash-critical column\n"+
				"     (action, outcome, actor_id, resource_id, timestamp) after the event was written.\n"+
				"  2. An event was physically deleted from the audit_events table, breaking the prev_hash link.\n"+
				"  3. An event was inserted out of sequence, shifting the chain.\n"+
				"  4. External tampering with the database by an unauthorised party.",
			v.BrokenCount)
		pdf.MultiCell(0, 5, incident, "LBR", "L", true)
		pdf.SetFillColor(255, 255, 255)
		pdf.SetDrawColor(0, 0, 0)
		pdf.SetTextColor(0, 0, 0)

		pdf.Ln(4)

		// Next steps
		pdf.SetFont("Arial", "B", 10)
		pdf.CellFormat(0, 6, "Recommended Next Steps", "", 1, "L", false, 0, "")
		pdf.SetFont("Arial", "", 9)
		steps := []string{
			"1. Preserve this report, the database and relevant application logs.",
			"2. Investigate the records and deployment changes around the reported break.",
			"3. Do not rewrite hashes to hide a break. This release has no re-anchor operation.",
			"4. A verification failure does not by itself identify the cause or responsible party.",
		}
		for _, s := range steps {
			pdf.MultiCell(0, 4.5, s, "", "L", false)
		}
	}

	pdf.Ln(6)
	pdf.SetFont("Arial", "I", 9)
	pdf.SetTextColor(80, 80, 80)
	pdf.MultiCell(0, 4.5,
		"Authenticated chain verification: GET "+in.VerifyURL+
			". Export signatures require a separately trusted instance public key.", "", "L", false)
	pdf.SetTextColor(0, 0, 0)
}

func renderSummaries(pdf *gofpdf.Fpdf, byAction, byActor map[string]int) {
	pdf.AddPage()
	heading(pdf, "2. Summary")

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 7, "Events by action", "", 1, "L", false, 0, "")
	renderKVTable(pdf, byAction, "Action", "Count")

	pdf.Ln(6)
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 7, "Events by actor type", "", 1, "L", false, 0, "")
	renderKVTable(pdf, byActor, "Actor type", "Count")
}

func renderEventLog(ctx context.Context, pdf *gofpdf.Fpdf, svc *Service, in PDFInput, brokenSet map[string]BrokenEvent) error {
	pdf.AddPage()
	heading(pdf, "3. Event log")

	if len(brokenSet) > 0 {
		pdf.SetFont("Arial", "I", 8)
		pdf.SetTextColor(160, 30, 30)
		pdf.CellFormat(0, 5,
			fmt.Sprintf("Events highlighted in red (%d) have chain integrity failures - see Section 1 for details.", len(brokenSet)),
			"", 1, "L", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(2)
	}

	headers := []string{"Timestamp (UTC)", "Actor", "Action", "Resource", "Outcome", "Event ID"}
	widths := []float64{32, 30, 30, 35, 18, 35}
	drawHeader := func() {
		pdf.SetFont("Arial", "B", 8)
		pdf.SetFillColor(235, 235, 235)
		pdf.SetTextColor(0, 0, 0)
		for i, h := range headers {
			pdf.CellFormat(widths[i], 6, h, "1", 0, "L", true, 0, "")
		}
		pdf.Ln(-1)
	}
	drawHeader()

	count := 0
	_, err := svc.repo.Walk(ctx, in.TenantID, in.From, in.To, func(e *AuditEvent) error {
		if pdf.GetY() > 270 {
			pdf.AddPage()
			drawHeader()
		}

		isBroken := false
		if _, ok := brokenSet[e.ID]; ok {
			isBroken = true
		}

		if isBroken {
			pdf.SetFillColor(255, 230, 230)
			pdf.SetTextColor(160, 30, 30)
		} else {
			pdf.SetFillColor(255, 255, 255)
			pdf.SetTextColor(0, 0, 0)
		}

		pdf.SetFont("Arial", "", 7.5)
		row := []string{
			e.Timestamp.UTC().Format("2006-01-02 15:04:05"),
			truncate(e.Actor.ID, 16),
			truncate(e.Action, 16),
			truncate(e.Resource.ID, 18),
			string(e.Outcome),
			truncate(e.ID, 18),
		}
		for i, v := range row {
			pdf.CellFormat(widths[i], 5, v, "1", 0, "L", isBroken, 0, "")
		}
		pdf.Ln(-1)
		count++
		return nil
	})
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	if err != nil {
		return err
	}
	if count == 0 {
		pdf.SetFont("Arial", "I", 9)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(0, 8, "No events in the selected period.", "", 1, "L", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
	}
	return nil
}

func renderLimitationsAppendix(pdf *gofpdf.Fpdf) {
	pdf.AddPage()
	heading(pdf, "Appendix A - Evidence limitations")
	pdf.SetFont("Arial", "", 10)
	for _, paragraph := range []string{
		"This report describes the recorded events and the verification result when the report was generated. It is not a compliance certification or a guarantee of agent safety.",
		"Only events delivered to Fact0 can be represented. Missing hooks, unavailable transcripts, failed deliveries and uninstrumented actions may leave gaps.",
		"The hash chain checks consistency of the stored history. An administrator with database and signing-key access can replace an entire history; a passing check does not rule this out.",
		"Evidence ZIP signatures bind the signed file bytes to an instance key. Verify against a public key obtained separately through a trusted channel, not only the key embedded in an archive.",
		"Replay reconstructs recorded activity and does not rerun an agent or external tools. This experimental release is maintained on a best-effort basis without an SLA.",
	} {
		pdf.MultiCell(0, 5, paragraph, "", "L", false)
		pdf.Ln(4)
	}
}

// ─── Helpers ───────────────────────────────────────────────

func heading(pdf *gofpdf.Fpdf, s string) {
	pdf.SetFont("Arial", "B", 16)
	pdf.SetTextColor(20, 20, 20)
	pdf.CellFormat(0, 10, s, "", 1, "L", false, 0, "")
	pdf.SetDrawColor(180, 180, 180)
	pdf.Line(15, pdf.GetY(), 195, pdf.GetY())
	pdf.Ln(4)
	pdf.SetTextColor(0, 0, 0)
}

func renderKVTable(pdf *gofpdf.Fpdf, m map[string]int, kHeader, vHeader string) {
	if len(m) == 0 {
		pdf.SetFont("Arial", "I", 9)
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(0, 6, "(no events)", "", 1, "L", false, 0, "")
		pdf.SetTextColor(0, 0, 0)
		return
	}
	pdf.SetFont("Arial", "B", 9)
	pdf.SetFillColor(235, 235, 235)
	pdf.CellFormat(120, 6, kHeader, "1", 0, "L", true, 0, "")
	pdf.CellFormat(0, 6, vHeader, "1", 1, "L", true, 0, "")
	pdf.SetFont("Arial", "", 9)

	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return m[keys[i]] > m[keys[j]] })
	for _, k := range keys {
		pdf.CellFormat(120, 5, k, "1", 0, "L", false, 0, "")
		pdf.CellFormat(0, 5, fmt.Sprintf("%d", m[k]), "1", 1, "R", false, 0, "")
	}
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	if n <= 1 {
		return s[:n]
	}
	return s[:n-1] + "…"
}
